name: Build dotnet image

on:
  push:
    paths:
    - 'dotnet-sdk/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to GitHub Package Registry
      run: echo "${{ secrets.SVIAT_DOCKER_PASSWORD }}" | docker login -u "${{ secrets.SVIAT_DOCKER_USERNAME }}" --password-stdin
    - name: Build the Docker image
      run: docker build . --file dotnet-sdk/Dockerfile --tag  sviatstetsiak/dotnet-sdk:zip-$(date +%Y-%m-%d)
    - name: Push the Docker image to the registry
      run: docker push sviatstetsiak/dotnet-sdk:zip-$(date +%Y-%m-%d)
