name: sonar-scanner-cli

on:
  push:
    paths:
    - "${GITHUB_WORKFLOW}/*"

env:
  ImageTag: "sviatstetsiak/${GITHUB_WORKFLOW}:${GITHUB_RUN_NUMBER}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to GitHub Package Registry
      run: echo "${{ secrets.SVIAT_DOCKER_PASSWORD }}" | docker login -u "${{ secrets.SVIAT_DOCKER_USERNAME }}" --password-stdin
    - name: Build the Docker image
      run: cd $GITHUB_WORKFLOW && docker build --tag  ${env.ImageTag} .
    - name: Push the Docker image to the registry
      run: docker push ${env.ImageTag}
