name: Show env

on:
  push:
    branches:
      - '*'
env:
  somevar: 'lastvar'
  somevar2: "${GITHUB_WORKFLOW}-test"
jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - name: Is variable exported?
        run: |
          echo "${{ env.somevar }}"
          echo "${{ env.somevar2 }}"
          
